[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
build_type = debug

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    knolleary/PubSubClient @ ^2.8
    arduino-libraries/NTPClient @ ^3.2.1
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    https://github.com/plerup/espsoftwareserial.git
    tzapu/WiFiManager @ ^2.0.17

build_flags =
    ; SIMULATION_MODE=true : le Node génère des mesures sans PZEM.
    ; Repasser à false quand le PZEM est câblé.
    -D SIMULATION_MODE=true
    -D DEVICE_ROLE=\"NODE\"
