; ================================================================
;  SENTINEL — Master Firmware — PlatformIO Configuration
; ================================================================
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Vitesse du moniteur série (Ctrl+Alt+S dans VSCode)
monitor_speed = 115200

; ─── Bibliothèques ──────────────────────────────────────────────
; PZEM-004T v3.0  : lecture des métriques électriques
; PubSubClient    : client MQTT léger pour ESP32
; ArduinoJson v7  : sérialisation JSON du payload
lib_deps =
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

; ─── Flags de compilation ────────────────────────────────────────
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DSIMULATION_MODE=true
