"""Initial baseline

Revision ID: fde4c262b560
Revises: 
Create Date: 2026-04-20 10:30:51.972971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fde4c262b560'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billingtariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_kwh', sa.Float(), nullable=False),
    sa.Column('max_kwh', sa.Float(), nullable=True),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('MASTER', 'NODE', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'FAULT', name='statusenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('master_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_mac_address'), 'device', ['mac_address'], unique=True)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('power_w', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('frequency_hz', sa.Float(), nullable=False),
    sa.Column('power_factor', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_device_mac_address'), table_name='device')
    op.drop_table('device')
    op.drop_table('billingtariff')
    # ### end Alembic commands ###
